import { VocabularyTopic } from '@/types';

export const vocabularyTopics: VocabularyTopic[] = [
  {
    id: 'physics',
    name: 'Physics',
    terms: [
      { term: 'net force', definition: 'The vector sum of all forces acting on an object' },
      { term: 'acceleration', definition: 'The rate of change of velocity over time' },
      { term: "Newton's Second Law", definition: 'F = ma; force equals mass times acceleration' },
      { term: 'friction', definition: 'A force that opposes the relative motion of surfaces in contact' },
      { term: 'normal force', definition: 'The perpendicular force exerted by a surface on an object' },
      { term: 'tension', definition: 'The pulling force transmitted through a string, rope, or cable' },
      { term: 'gravitational force', definition: 'The attractive force between objects with mass' },
      { term: 'free body diagram', definition: 'A diagram showing all forces acting on an object' },
      { term: 'equilibrium', definition: 'A state where the net force on an object is zero' },
      { term: 'inertia', definition: 'The tendency of an object to resist changes in its motion' },
      { term: 'velocity', definition: 'The rate of change of position with respect to time; speed with direction' },
      { term: 'momentum', definition: 'The product of an object\'s mass and velocity' },
      { term: 'kinetic energy', definition: 'Energy an object has due to its motion' },
      { term: 'potential energy', definition: 'Stored energy due to position or configuration' },
      { term: 'work', definition: 'Energy transferred when a force moves an object' },
      { term: 'power', definition: 'The rate at which work is done or energy is transferred' },
      { term: 'wavelength', definition: 'The distance between successive crests of a wave' },
      { term: 'frequency', definition: 'The number of waves that pass a point per unit time' },
      { term: 'refraction', definition: 'The bending of light or waves when passing from one medium to another' },
      { term: 'reflection', definition: 'The bouncing back of light or waves from a surface' },
    ],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    terms: [
      { term: 'reactant', definition: 'A substance that undergoes change in a chemical reaction' },
      { term: 'product', definition: 'A substance formed as a result of a chemical reaction' },
      { term: 'catalyst', definition: 'A substance that speeds up a reaction without being consumed' },
      { term: 'activation energy', definition: 'The minimum energy required to start a chemical reaction' },
      { term: 'exothermic', definition: 'A reaction that releases heat to the surroundings' },
      { term: 'endothermic', definition: 'A reaction that absorbs heat from the surroundings' },
      { term: 'equilibrium constant', definition: 'The ratio of product concentrations to reactant concentrations at equilibrium' },
      { term: 'rate law', definition: 'An equation relating reaction rate to reactant concentrations' },
      { term: 'oxidation', definition: 'The loss of electrons in a chemical reaction' },
      { term: 'reduction', definition: 'The gain of electrons in a chemical reaction' },
      { term: 'molecule', definition: 'Two or more atoms bonded together' },
      { term: 'atom', definition: 'The smallest unit of an element that retains its properties' },
      { term: 'electron', definition: 'A negatively charged subatomic particle' },
      { term: 'proton', definition: 'A positively charged subatomic particle in the nucleus' },
      { term: 'neutron', definition: 'A neutral subatomic particle in the nucleus' },
      { term: 'periodic table', definition: 'A chart organizing elements by atomic number and properties' },
      { term: 'valence', definition: 'The combining capacity of an element; electrons in the outer shell' },
      { term: 'ionic bond', definition: 'A bond formed by the transfer of electrons between atoms' },
      { term: 'covalent bond', definition: 'A bond formed by the sharing of electron pairs between atoms' },
      { term: 'pH', definition: 'A measure of acidity or alkalinity; scale from 0 to 14' },
    ],
  },
  {
    id: 'biology',
    name: 'Biology',
    terms: [
      { term: 'organism', definition: 'Any living thing, such as a plant, animal, or bacterium' },
      { term: 'organisms', definition: 'Living things that carry out life processes' },
      { term: 'ecology', definition: 'The study of how organisms interact with each other and their environment' },
      { term: 'ecosystem', definition: 'A community of organisms and their physical environment' },
      { term: 'food chain', definition: 'A sequence of organisms through which energy and nutrients flow' },
      { term: 'producer', definition: 'An organism that makes its own food, e.g. plants via photosynthesis' },
      { term: 'consumer', definition: 'An organism that eats other organisms for energy' },
      { term: 'decomposer', definition: 'An organism that breaks down dead matter and recycles nutrients' },
      { term: 'habitat', definition: 'The natural environment where an organism lives' },
      { term: 'photosynthesis', definition: 'Process by which plants convert light energy to chemical energy' },
      { term: 'cellular respiration', definition: 'Process of breaking down glucose to produce ATP' },
      { term: 'mitochondria', definition: 'Organelle that produces ATP through cellular respiration' },
      { term: 'ribosome', definition: 'Cellular structure responsible for protein synthesis' },
      { term: 'cell membrane', definition: 'Phospholipid bilayer that controls what enters and exits the cell' },
      { term: 'nucleus', definition: 'Contains genetic material and controls cell activities' },
      { term: 'ATP', definition: 'Adenosine triphosphate; the energy currency of cells' },
      { term: 'osmosis', definition: 'Movement of water across a semipermeable membrane' },
      { term: 'Golgi apparatus', definition: 'Organelle that modifies, packages, and ships proteins' },
      { term: 'endoplasmic reticulum', definition: 'Network of membranes involved in protein and lipid synthesis' },
      { term: 'DNA', definition: 'Deoxyribonucleic acid; carries genetic instructions' },
      { term: 'RNA', definition: 'Ribonucleic acid; involved in protein synthesis and gene expression' },
      { term: 'chromosome', definition: 'Thread-like structure of DNA and protein carrying genes' },
      { term: 'evolution', definition: 'Change in heritable traits of a population over time' },
      { term: 'natural selection', definition: 'Process by which organisms better adapted to the environment tend to survive and reproduce' },
      { term: 'biodiversity', definition: 'The variety of life in an ecosystem or on Earth' },
    ],
  },
  {
    id: 'calculus',
    name: 'Calculus',
    terms: [
      { term: 'derivative', definition: 'The instantaneous rate of change of a function' },
      { term: 'limit', definition: 'The value a function approaches as input approaches a value' },
      { term: 'chain rule', definition: 'Method for finding the derivative of composite functions' },
      { term: 'product rule', definition: 'Method for finding the derivative of a product of functions' },
      { term: 'quotient rule', definition: 'Method for finding the derivative of a quotient of functions' },
      { term: 'implicit differentiation', definition: 'Finding derivatives when y is not explicitly defined' },
      { term: 'critical point', definition: 'Point where the derivative equals zero or is undefined' },
      { term: 'inflection point', definition: 'Point where the concavity of a function changes' },
      { term: 'tangent line', definition: 'A line that touches a curve at exactly one point' },
      { term: 'second derivative', definition: 'The derivative of the derivative; measures concavity' },
      { term: 'integral', definition: 'The area under a curve; the reverse of differentiation' },
      { term: 'antiderivative', definition: 'A function whose derivative is the given function' },
      { term: 'definite integral', definition: 'An integral with upper and lower limits; gives a number' },
      { term: 'indefinite integral', definition: 'An integral without limits; gives a family of functions' },
      { term: 'u-substitution', definition: 'A technique for simplifying integrals by substituting a variable' },
      { term: 'area under the curve', definition: 'The geometric interpretation of the definite integral' },
      { term: 'related rates', definition: 'Finding the rate of change of one quantity given the rate of another' },
      { term: 'optimization', definition: 'Finding maximum or minimum values of a function' },
      { term: 'Riemann sum', definition: 'An approximation of area using rectangles' },
      { term: 'fundamental theorem', definition: 'Links differentiation and integration; integral of derivative gives net change' },
    ],
  },
  {
    id: 'algebra',
    name: 'Algebra',
    terms: [
      { term: 'variable', definition: 'A symbol, usually a letter, representing an unknown or changing value' },
      { term: 'equation', definition: 'A statement that two expressions are equal' },
      { term: 'inequality', definition: 'A statement that one expression is less than, greater than, or not equal to another' },
      { term: 'linear equation', definition: 'An equation whose graph is a straight line' },
      { term: 'quadratic equation', definition: 'An equation of the form ax² + bx + c = 0' },
      { term: 'slope', definition: 'The steepness of a line; rise over run' },
      { term: 'y-intercept', definition: 'The point where a line crosses the y-axis' },
      { term: 'factor', definition: 'A number or expression that divides evenly into another' },
      { term: 'factoring', definition: 'Writing an expression as a product of simpler expressions' },
      { term: 'polynomial', definition: 'An expression with variables and coefficients using only addition, subtraction, and non-negative integer exponents' },
      { term: 'exponent', definition: 'A number showing how many times a base is multiplied by itself' },
      { term: 'quadratic formula', definition: 'x = (-b ± √(b² - 4ac)) / 2a; solves ax² + bx + c = 0' },
      { term: 'parabola', definition: 'The U-shaped graph of a quadratic function' },
      { term: 'function', definition: 'A relation that assigns exactly one output to each input' },
      { term: 'domain', definition: 'The set of all possible inputs to a function' },
      { term: 'range', definition: 'The set of all possible outputs of a function' },
      { term: 'system of equations', definition: 'Two or more equations with the same variables solved together' },
      { term: 'substitution', definition: 'Solving a system by replacing one variable with an expression' },
      { term: 'elimination', definition: 'Solving a system by adding or subtracting equations to remove a variable' },
      { term: 'absolute value', definition: 'The distance of a number from zero; always non-negative' },
    ],
  },
  {
    id: 'history',
    name: 'History',
    terms: [
      { term: 'secession', definition: 'The act of withdrawing from a union or political body' },
      { term: 'Confederacy', definition: 'The Southern states that seceded from the Union in the Civil War' },
      { term: 'Emancipation Proclamation', definition: 'Lincoln\'s order freeing slaves in Confederate states' },
      { term: 'abolition', definition: 'The movement to end slavery' },
      { term: 'Reconstruction', definition: 'Period of rebuilding the South after the Civil War' },
      { term: "states' rights", definition: 'The belief that states should have more power than the federal government' },
      { term: 'Union', definition: 'The Northern states during the Civil War' },
      { term: 'Gettysburg', definition: 'Turning point battle of the Civil War' },
      { term: 'Antietam', definition: 'Bloodiest single-day battle in American history' },
      { term: 'Appomattox', definition: 'Location where Lee surrendered to Grant' },
      { term: 'Revolution', definition: 'A fundamental change in power or political structure' },
      { term: 'Constitution', definition: 'The supreme law of the United States; framework for government' },
      { term: 'Declaration of Independence', definition: '1776 document declaring American colonies independent from Britain' },
      { term: 'colonial', definition: 'Relating to or characteristic of a colony' },
      { term: 'industrialization', definition: 'The development of industries and manufacturing on a large scale' },
      { term: 'suffrage', definition: 'The right to vote in political elections' },
      { term: 'civil rights', definition: 'Rights of citizens to political and social equality' },
      { term: 'Cold War', definition: 'Period of tension between the US and Soviet Union after WWII' },
      { term: 'democracy', definition: 'Government by the people, typically through elected representatives' },
      { term: 'federalism', definition: 'Division of power between national and state governments' },
    ],
  },
  {
    id: 'english',
    name: 'English',
    terms: [
      { term: 'metaphor', definition: 'A figure of speech comparing two unlike things without using like or as' },
      { term: 'simile', definition: 'A figure of speech comparing two things using like or as' },
      { term: 'personification', definition: 'Giving human qualities to non-human things' },
      { term: 'alliteration', definition: 'Repetition of the same sound at the start of nearby words' },
      { term: 'theme', definition: 'The central idea or message of a work' },
      { term: 'plot', definition: 'The sequence of events in a story' },
      { term: 'character', definition: 'A person or being in a narrative' },
      { term: 'setting', definition: 'The time and place in which a story occurs' },
      { term: 'conflict', definition: 'The struggle between opposing forces in a story' },
      { term: 'resolution', definition: 'The point where the conflict is resolved' },
      { term: 'protagonist', definition: 'The main character; the hero or central figure' },
      { term: 'antagonist', definition: 'The character or force that opposes the protagonist' },
      { term: 'irony', definition: 'A contrast between expectation and reality' },
      { term: 'symbolism', definition: 'The use of symbols to represent ideas or qualities' },
      { term: 'tone', definition: 'The author\'s attitude toward the subject or audience' },
      { term: 'mood', definition: 'The feeling or atmosphere a work creates for the reader' },
      { term: 'foreshadowing', definition: 'Hints about what will happen later in the story' },
      { term: 'point of view', definition: 'The perspective from which a story is told' },
      { term: 'narrator', definition: 'The voice or character telling the story' },
      { term: 'climax', definition: 'The turning point or moment of highest tension in a plot' },
    ],
  },
  {
    id: 'geography',
    name: 'Geography',
    terms: [
      { term: 'latitude', definition: 'Distance north or south of the equator, measured in degrees' },
      { term: 'longitude', definition: 'Distance east or west of the prime meridian, measured in degrees' },
      { term: 'equator', definition: 'The imaginary line at 0° latitude dividing Earth into Northern and Southern Hemispheres' },
      { term: 'hemisphere', definition: 'Half of Earth; Northern, Southern, Eastern, or Western' },
      { term: 'climate', definition: 'Long-term patterns of weather in a region' },
      { term: 'weather', definition: 'Short-term conditions of the atmosphere' },
      { term: 'topography', definition: 'The shape and features of the land surface' },
      { term: 'plateau', definition: 'A raised area of flat land' },
      { term: 'peninsula', definition: 'Land surrounded by water on three sides' },
      { term: 'archipelago', definition: 'A group of islands' },
      { term: 'tributary', definition: 'A river or stream that flows into a larger river' },
      { term: 'delta', definition: 'Landform at the mouth of a river where it splits into smaller channels' },
      { term: 'population', definition: 'The number of people living in an area' },
      { term: 'migration', definition: 'Movement of people from one place to another' },
      { term: 'urban', definition: 'Relating to cities or densely populated areas' },
      { term: 'rural', definition: 'Relating to the countryside or sparsely populated areas' },
      { term: 'region', definition: 'An area with common characteristics that set it apart' },
      { term: 'continent', definition: 'One of Earth\'s large landmasses' },
      { term: 'time zone', definition: 'A region that observes a uniform standard time' },
      { term: 'cartography', definition: 'The science and art of making maps' },
    ],
  },
  {
    id: 'computer-science',
    name: 'Computer Science',
    terms: [
      { term: 'algorithm', definition: 'A step-by-step procedure for solving a problem' },
      { term: 'variable', definition: 'A named storage location that holds a value' },
      { term: 'function', definition: 'A reusable block of code that performs a task' },
      { term: 'loop', definition: 'A structure that repeats code until a condition is met' },
      { term: 'array', definition: 'A data structure that stores a collection of elements' },
      { term: 'string', definition: 'A sequence of characters; text data' },
      { term: 'boolean', definition: 'A data type with only two values: true or false' },
      { term: 'debugging', definition: 'Finding and fixing errors in code' },
      { term: 'syntax', definition: 'The rules that define the structure of a programming language' },
      { term: 'binary', definition: 'Base-2 number system using only 0 and 1' },
      { term: 'API', definition: 'Application Programming Interface; allows programs to communicate' },
      { term: 'database', definition: 'An organized collection of data stored and accessed electronically' },
      { term: 'server', definition: 'A computer or program that provides services to other programs or devices' },
      { term: 'client', definition: 'A program or device that requests services from a server' },
      { term: 'input', definition: 'Data or signals entered into a system' },
      { term: 'output', definition: 'Data or results produced by a system' },
      { term: 'conditional', definition: 'A statement that executes different code based on a condition' },
      { term: 'recursion', definition: 'A function that calls itself to solve a problem' },
      { term: 'data structure', definition: 'A way of organizing and storing data' },
      { term: 'programming', definition: 'The process of writing instructions for a computer' },
    ],
  },
  {
    id: 'marketing',
    name: 'Marketing',
    terms: [
      { term: 'marketing', definition: 'Creating value for customers by meeting their needs and wants' },
      { term: 'Four Ps', definition: 'Product, Price, Promotion, and Place; key marketing elements' },
      { term: 'target market', definition: 'The specific group of consumers a business aims to reach' },
      { term: 'market segmentation', definition: 'Dividing a market into distinct groups of buyers' },
      { term: 'brand awareness', definition: 'The extent to which consumers recognize a brand' },
      { term: 'value proposition', definition: 'The unique value a product or service offers to customers' },
      { term: 'customer acquisition', definition: 'The process of gaining new customers' },
      { term: 'conversion rate', definition: 'The percentage of visitors who take a desired action' },
      { term: 'ROI', definition: 'Return on Investment; a measure of profitability' },
      { term: 'advertising', definition: 'Paid promotion of products or services through media' },
      { term: 'campaign', definition: 'A coordinated series of actions to achieve a marketing goal' },
      { term: 'analytics', definition: 'The analysis of data to understand and improve performance' },
      { term: 'social media', definition: 'Online platforms for sharing content and engaging with audiences' },
      { term: 'SEO', definition: 'Search Engine Optimization; improving visibility in search results' },
      { term: 'demographics', definition: 'Statistical data about a population, such as age or income' },
      { term: 'competitor', definition: 'A business that offers similar products or services' },
      { term: 'pricing', definition: 'The strategy of setting prices for products or services' },
      { term: 'promotion', definition: 'Activities that communicate the benefits of a product and persuade customers' },
      { term: 'distribution', definition: 'Getting products from producer to consumer' },
      { term: 'customer retention', definition: 'Keeping existing customers and encouraging repeat business' },
    ],
  },
];

export function getTopicById(id: string): VocabularyTopic | undefined {
  return vocabularyTopics.find(topic => topic.id === id);
}

export function searchTermsInText(text: string, topic: VocabularyTopic): string[] {
  const foundTerms: string[] = [];
  const lowerText = text.toLowerCase();
  
  for (const { term } of topic.terms) {
    if (lowerText.includes(term.toLowerCase())) {
      foundTerms.push(term);
    }
  }
  
  return foundTerms;
}
